version: '3'

services:
  db:
    image: postgres
    container_name: hello-to-db
    environment:
      POSTGRES_USER: prizkalla
      POSTGRES_PASSWORD: hello
      POSTGRES_DB: books
    volumes:
      - ~/dev/postgres/db:/var/lib/postgresql/data
    networks:
      - my-network

  helloql:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ~/Desktop/dev/training/graphql/strawberry-demo:/usr/src/app
    depends_on:
      - db
    ports:
      - "8080:8000"
    networks:
      - my-network

networks:
  my-network:
    external: true